### ISSUE TITLE
How to do SSR?

### ISSUE THREAD

**Issue by zerkalica** [type-route/type-route#10]
How to use type-route with server side rendering?

For example: https://github.com/bitttttten/oatmilk/blob/master/docs/server-rendering.md

**Comment by bradenhs** [comment]
Great question. Type Route almost has support for server side rendering. Basically when creating the router when doing server side rendering you'll want to use a "memory" router type instead of a "browser" router type. From there, however, it currently isn't possible to set the initial route from a given url using the "memory" router type. That'll take a small API change to be possible. Stay tuned. This is an important use case and I hope to get support out for it soon.

**Comment by bradenhs** [comment]
@zerkalica latest release has support for server-side rendering. I put together a brief guide explaining how to do it here: https://www.type-route.org/docs/guides/server-side-rendering. Feel free to reopen this issue if the guide isn't clear enough or open another issue if you encounter any bugs with the new feature.
